#!/bin/bash
set -e
source $(pwd)/.prj
### DO NOT USE '; ' in variables list! Only ';'
### pointers MUST BE like 'int** s'. NOT like 'int **s' nor 'int ** s'
args=("$@")
dd=0 #delete default constructor
dc=0 #delete copy constructor with operator=
dm=0 #delete move constructor with operator=
vi=0 #pr(I)vate variables flag
vo=0 #pr(O)tected variables flag
asi=0 #(A)dd public (S)etters to pr(I)vate variables
agi=0 #(A)dd public (G)etters to pr(I)vate variables
aso=0 #(A)dd public (S)etters to pr(O)tected variables
ago=0 #(A)dd public (G)etters to pr(O)tected variables
priv_vars=""
prot_vars=""
flag0=0
template_flag=0
tt=0
flag_cl=0
declare -a classes
for opt in ${args[@]}; do
	if [ "$opt" == "-t" ]; then
		template_flag=1
		tt=1
		continue
	fi
	if [ $template_flag -eq 1 ]; then
		if [ "$opt" == "-dd" ] || [ "$opt" == "-dc" ] || [ "$opt" == "-dm" ] || [ "$opt" == "-vi" ] || [ "$opt" == "-vo" ]; then 
			template_flag=0
		else
			temps[${#temps[*]}]="$opt"
			continue
		fi
	fi
    if [ $vi -eq 0 -a $vo -eq 0 ]; then
		if [[ "$opt" == "-dd" ]]; then
		    dd=1
		elif [[ "$opt" == "-dc" ]]; then                                                                           
		    dc=1
		elif [[ "$opt" == "-dm" ]]; then                                                                           
		    dm=1
		elif [[ "$opt" == "-vi" ]]; then
			vi=1
		elif [[ "$opt" == "-vo" ]]; then
			vo=1
		else
			classes[${#classes[*]}]="$opt"
		fi
	elif [ $vi -eq 1 -a $vo -eq 0 ]; then
		if [[ "$opt" == "-vo" ]]; then
			vo=1
		elif [[ "$opt" == "-as" ]]; then
			asi=1
		elif [[ "$opt" == "-ag" ]]; then
			agi=1
		else
			priv_vars="${priv_vars} $opt"
		fi
	elif [ $vi -eq 0 -a $vo -eq 1 ]; then
		if [[ "$opt" == "-vi" ]]; then
			vi=1
		elif [[ "$opt" == "-as" ]]; then
			aso=1
		elif [[ "$opt" == "-ag" ]]; then
			ago=1
		else
			prot_vars="${prot_vars} $opt"
		fi
	elif [ $vi -eq 1 -a $vo -eq 1 ]; then
		if [ -z "$prot_vars" -o $flag0 -eq 1 ]; then
			if [[ "$opt" == "-as" ]]; then
				aso=1
			elif [[ "$opt" == "-ag" ]]; then
				ago=1
			else
				prot_vars="${prot_vars} $opt"
			fi
			flag0=1
		elif [ -z "$priv_vars" -o $flag0 -eq 2 ]; then 
			if [[ "$opt" == "-as" ]]; then
				asi=1
			elif [[ "$opt" == "-ag" ]]; then
				agi=1
			else	
				priv_vars="${priv_vars} $opt"
			fi
			flag0=2
		fi
	fi
done
template_flag=$tt
declare -a i_types
declare -a i_vars
declare -a o_types
declare -a o_vars
priv_vars=`echo $priv_vars | sed "s/;/;\n/g"`
OLD_IFS=${IFS}; 
IFS=$'\x0a'; 
for i in $priv_vars; do 
	i_types[${#i_types[*]}]=`echo $i | rev | cut -d ' ' -f2- | rev | sed "s/;//"`; 
	i_vars[${#i_vars[*]}]=`echo $i | rev | cut -d ' ' -f-1 | rev | sed "s/;//"`;
done; 
IFS=${OLD_IFS}
priv_vars=`echo "$priv_vars" | sed "s|^|        /**\\\brief */\n        |g"`
#priv_vars=`echo "$priv_vars" | sed 's/$/\\/g'`

prot_vars=`echo $prot_vars | sed "s/;/;\n/g"`
OLD_IFS=${IFS}; 
IFS=$'\x0a'; 
for i in $prot_vars; do 
	o_types[${#o_types[*]}]=`echo $i | rev | cut -d ' ' -f2- | rev | sed "s/;//"`; 
	o_vars[${#o_vars[*]}]=`echo $i | rev | cut -d ' ' -f-1 | rev | sed "s/;//"`;
done; 
IFS=${OLD_IFS}
prot_vars=`echo "$prot_vars" | sed "s|^|        /**\\\brief */\n        |g"`
#priv_vars=`echo "$priv_vars" | sed 's/$/\\/g'`
class_name=${classes[0]}
classes=("${classes[@]:1}")
flag=0
declare -a class_mask
class_counter=0
if [ ${#classes[@]} -ne 0 ]; then
	#separator=", " # e.g. constructing regex, pray it does not contain %s
	#regex="$( printf "${separator}%s" "${classes[@]}" )"
	#parents="${regex:${#separator}}" # remove leading separator
	inh_type=0 #nodefault
	for ((a=0; a <= ${#classes[@]} - 1; a++)); do
		class_mask[$a]=0
		if [ ${classes[a]} == "-u" ];then #public
			inh_type=1
		elif [ ${classes[a]} == "-o" ];then #protected
			inh_type=2
		elif [ ${classes[a]} == "-i" ];then #private
			inh_type=3
		elif [ ${classes[a]} == "-vu" ];then #virtual public
			inh_type=4
		else
			class_mask[$a]=1 # zeros are dividers
			if [ $inh_type -eq 0 ]; then
				parents="$parents ${classes[a]}"
			else
				if [ $inh_type -eq 1 ]; then
					parents="$parents, public ${classes[a]}"
					inh_type=0
				elif [ $inh_type -eq 2 ]; then
					parents="$parents, protected ${classes[a]}"
					inh_type=0
				elif [ $inh_type -eq 3 ]; then
					parents="$parents, private ${classes[a]}"
					inh_type=0
				elif [ $inh_type -eq 4 ]; then
					parents="$parents, virtual public ${classes[a]}"
					inh_type=0
				fi
			fi
		fi
	done
	parents=`echo "$parents" | sed 's/\,//'`
	flag=1
fi
if [ -e "include" -a -e "src" ]; then
	if [ -e "include/$class_name.hpp" -o -e "src/$class_name.cpp" -o -e "include/${class_name}_impl.hpp" ]; then
		echo "File exists. Exit"
		exit
	fi
	d=$(date +%x\ %X)
	inc="include/$class_name.hpp"
	src=""
	m4 -D cls=$class_name -D d="$d" -D dm=$dm -D dd=$dd -D dc=$dc -D auth="$auth" /etc/cpprj/cls_dummy.hpp.m4 > $inc
	if [ $template_flag -eq 0 ]; then
	src="src/$class_name.cpp"
		m4 -D cls=$class_name -D d="$d" -D dm=$dm -D dd=$dd -D dc=$dc -D auth="$auth" -D temp1="" -D temp2="" /etc/cpprj/cls_dummy.cpp.m4 > $src
	else
		if [ ${#temps[@]} -ne 0 ]; then
			separator1=", " # e.g. constructing regex, pray it does not contain %s
			regex="$( printf "${separator1}%s" "${temps[@]}" )"
			templates1="${regex:${#separator1}}" # remove leading separator
			separator2=", class " # e.g. constructing regex, pray it does not contain %s
			regex="$( printf "${separator2}%s" "${temps[@]}" )"
			templates2="${regex:${#separator2}}" # remove leading separator
			templates2=" class ${templates2}"
		fi 
		src="include/${class_name}_impl.hpp"
		m4 -D cls=$class_name -D d="$d" -D dm=$dm -D dd=$dd -D dc=$dc -D auth="$auth" -D temp2="\`\`<$templates1>''" -D temp1="\`\`template<$templates2 >''" /etc/cpprj/cls_dummy.cpp.m4 > $src
		sed -i "7d" $inc
		sed -i "7i#pragma once" $src
		echo "#include \"${class_name}_impl.hpp\"" >> $inc
		
	fi
	cls=""
	for ((a = ${#classes[@]} - 1;a >= 0; a--)); do
		if [ ${class_mask[a]} -eq 1 ]; then 
			cls="$cls ${classes[a]}"	
		else
			cls=`echo "$cls" | sed "s|<*>||g" | sed "s|::|/|g" | sed -e 's/^.\{1\}//'`
			sed -i "/#pragma once/ a #include \"${cls}.hpp\"" $inc
			if [ -w "include/${cls}.hpp" ]; then
				str=`sed -ne "/virtual ~$cls/p" include/$cls.hpp`
				if [ -z "$str" ]; then
					sed -i "s|~$cls|virtual ~$cls|" include/${cls}.hpp
				fi
			fi
			cls=""
		fi
	done
	parents1=`echo $parents | sed 's|, |(), |g'`
	parents2=`echo $parents1 | sed 's|public ||g' | sed  's|protected ||g' | sed 's|private ||g' | sed 's|virtual ||g'`
	if [ $flag -eq 1 ]; then
		sed -i "s|() cls_parents|(): $parents2|g" $src
		sed -i "s|^cls_parents|$parents2|g" $src
		sed -i "s|cls_parents|\: $parents|g" $inc
	else
		sed -i "s|cls_parents(), ||g" $src
		sed -i "s|cls_parents()||g" $src                                          
		sed -i "s|cls_parents||g" $inc
	fi
	if [ $template_flag -eq 0 ]; then
		sed -i "s|(SOURCE_FILES|(SOURCE_FILES\n\t\tsrc/$class_name.cpp|" CMakeLists.txt
	fi
	if [ $vi -eq 1 ]; then
		priv_vars=${priv_vars//\\/\\\\}
		priv_vars=${priv_vars//&/\\&}
		priv_vars=${priv_vars//|/\\|}
		priv_vars=${priv_vars//;/\\;\\}
		priv_vars=${priv_vars//\//\\\/\\}
		sed -i "s|\/\*private data\*\/|$priv_vars |" $inc
		for ((a = ${#i_vars[@]} - 1; a>=0; a--)); do
		tmp_str=`echo "${i_types[a]}" | sed -n "/static/p"`
			if [ -n "$tmp_str" ]; then
				if [ $template_flag -eq 0 ]; then
					sed -i "/#include <utility>/ a ${i_types[a]} $class_name::${i_vars[a]};\n" $src
				else
					sed -i "/#include <utility>/ a template<$templates2>\n${i_types[a]} $class_name<$templates1>::${i_vars[a]};\n" $src
				fi
			i_types[a]=`echo "${i_types[a]}" | sed "s/static //"`
			fi
			i_types[a]=`echo "${i_types[a]}" | sed "s/mutable //"`
		done
		if [ $asi -eq 1 -a $agi -eq 1 ]; then 
			for ((a = ${#i_vars[@]} - 1; a>=0; a--)); do
				sed -i "/\/\/pub functions/ a \\\t\t\/**\t\\\brief Setter method for variable ${i_vars[a]}\n\t\t\t\\\param [in] x - \n\t\t*\/\n\t\t void set_${i_vars[a]} (const ${i_types[a]} & x);" $inc
				sed -i "/\/\/pub functions/ a \\\t\t\/**\t\\\brief Getter method for variable ${i_vars[a]}\n\t\t\t\\\return Value of variable ${i_vars[a]} \n\t\t*\/\n\t\t ${i_types[a]} get_${i_vars[a]} () const;" $inc
				if [ $template_flag -eq 0 ]; then
					sed -i "/\/\/methods/ a void $class_name::set_${i_vars[a]} (const ${i_types[a]} & x)\n{\n\t${i_vars[a]} = x;\n}" $src
					sed -i "/\/\/methods/ a ${i_types[a]} $class_name::get_${i_vars[a]} () const \n{\n\treturn ${i_vars[a]}\;\n}" $src
				else
					sed -i "/\/\/methods/ a template<$templates2> \nvoid $class_name<$templates1>::set_${i_vars[a]} (const ${i_types[a]} & x)\n{\n\t${i_vars[a]} = x;\n}" $src
					sed -i "/\/\/methods/ a template<$templates2> \n${i_types[a]} $class_name<$templates1>::get_${i_vars[a]} () const\n{\n\treturn ${i_vars[a]}\;\n}" $src
				fi
			done
		elif [ $asi -eq 1 ]; then
			for ((a = ${#i_vars[@]} - 1; a>=0; a--)); do                                                            
				sed -i "/\/\/pub functions/ a \\\t\t\/**\t\\\brief Setter method for variable ${i_vars[a]}\n\t\t\t\\\param [in] x - \n\t\t*/\n\t\t void set_${i_vars[a]} (const ${i_types[a]} & x);" $inc
				if [ $template_flag -eq 0 ]; then
					sed -i "/\/\/methods/ a void $class_name::set_${i_vars[a]} (const ${i_types[a]} & x)\n{\n\t${i_vars[a]} = x;\n}" $src
				else
					sed -i "/\/\/methods/ a template<$templates2> void $class_name<$templates1>::set_${i_vars[a]} (const ${i_types[a]} & x)\n{\n\t${i_vars[a]} = x;\n}" $src
				fi
			done
		elif [ $agi -eq 1 ]; then
			for ((a = ${#i_vars[@]} - 1; a>=0; a--)); do
				sed -i "/\/\/pub functions/ a \\\t\t\/**\t\\\brief Getter method for variable ${i_vars[a]}\n\t\t\t\\\return Value of variable ${i_vars[a]} \n\t\t*/\n\t\t ${i_types[a]} get_${i_vars[a]} () const;" $inc
				if [ $template_flag -eq 0 ]; then
					sed -i "/\/\/methods/ a ${i_types[a]} $class_name::get_${i_vars[a]} () const\n{\n\treturn ${i_vars[a]}\;\n}" $src
				else
					sed -i "/\/\/methods/ a template<$templates2> ${i_types[a]} $class_name<$templates1>::get_${i_vars[a]} () const\n{\n\treturn ${i_vars[a]}\;\n}" $src
				fi
			done
		fi
	fi
	if [ $vo -eq 1 ]; then
		prot_vars=${prot_vars//\\/\\\\}
		prot_vars=${prot_vars//&/\\&}
		prot_vars=${prot_vars//|/\\|}
		prot_vars=${prot_vars//;/\\;\\}
		prot_vars=${prot_vars//\//\\\/\\}
		sed -i "s|\/\*protected data\*\/|$prot_vars |" $inc
		for ((a = ${#o_vars[@]}-1; a>=0; a--)); do
			tmp_str=`echo "${o_types[a]}" | sed -n "/static/p"`
			if [ -n "$tmp_str" ]; then
				if [ $template_flag -eq 0 ]; then
					sed -i "/#include <utility>/ a ${o_types[a]} $class_name::${o_vars[a]};\n" $src
				else
					sed -i "/#include <utility>/ a template<$templates2>\n${o_types[a]} $class_name<$templates1>::${o_vars[a]};\n" $src
				fi
			o_types[a]=`echo "${o_types[a]}" | sed "s/static //"`
			fi
			o_types[a]=`echo "${o_types[a]}" | sed "s/mutable //"`
		done
		if [ $aso -eq 1 -a $ago -eq 1 ]; then 
			for ((a = ${#o_vars[@]} - 1; a>=0; a--)); do
				sed -i "/\/\/pub functions/ a \\\t\t\/**\t\\\brief Setter method for variable ${o_vars[a]}\n\t\t\t\\\param [in] x - \n\t\t*/\n\t\t void set_${o_vars[a]} (const ${o_types[a]} & x);" $inc
				sed -i "/\/\/pub functions/ a \\\t\t\/**\t\\\brief Getter method for variable ${o_vars[a]}\n\t\t\t\\\return Value of variable ${o_vars[a]} \n\t\t*/\n\t\t ${o_types[a]} get_${o_vars[a]} () const;" $inc
				if [ $template_flag -eq 0 ]; then
					sed -i "/\/\/methods/ a void $class_name::set_${o_vars[a]} (const ${o_types[a]} & x)\n{\n\t${o_vars[a]} = x;\n}" $src
					sed -i "/\/\/methods/ a ${o_types[a]} $class_name::get_${o_vars[a]} () const\n{\n\treturn ${o_vars[a]}\;\n}" $src
				else
					sed -i "/\/\/methods/ a template<$templates2>\nvoid $class_name<$templates1>::set_${o_vars[a]} (const ${o_types[a]} & x)\n{\n\t${o_vars[a]} = x;\n}" $src
					sed -i "/\/\/methods/ a template<$templates2>\n${o_types[a]} $class_name<$templates1>::get_${o_vars[a]} () const\n{\n\treturn ${o_vars[a]}\;\n}" $src
				fi
			done
		elif [ $asi -eq 1 ]; then
			for ((a = ${#o_vars[@]} - 1; a>=0; a--)); do                                                            
				sed -i "/\/\/pub functions/ a \\\t\t\/**\t\\\brief Setter method for variable ${o_vars[a]}\n\t\t\t\\\param [in] x - \n\t\t*/\n\t\t void set_${o_vars[a]} (const ${o_types[a]} & x);" $inc
				
				if [ $template_flag -eq 0 ]; then
					sed -i "/\/\/methods/ a void $class_name::set_${o_vars[a]} (const ${o_types[a]} & x)\n{\n\t${o_vars[a]} = x;\n}" $src
				else
					sed -i "/\/\/methods/ a template<$template2>\nvoid $class_name<$templates1>::set_${o_vars[a]} (const ${o_types[a]} & x)\n{\n\t${o_vars[a]} = x;\n}" $src
				fi
			done
		elif [ $agi -eq 1 ]; then
			for ((a = ${#i_vars[@]} - 1; a>=0; a--)); do                                                            
				sed -i "/\/\/pub functions/ a \\\t\t\/**\t\\\brief Getter method for variable ${o_vars[a]}\n\t\t\t\\\return Value of variable ${o_vars[a]} \n\t\t*/\n\t\t ${o_types[a]} get_${o_vars[a]} () const;" $inc
				if [ $template_flag -eq 0 ]; then
					sed -i "/\/\/methodss/ a ${o_types[a]} $class_name::get_${o_vars[a]} () const\n{\n\treturn ${o_vars[a]}\;\n}" $src
				else
					sed -i "/\/\/methodss/ a template<$templates2>\n${o_types[a]} $class_name<$templates1>::get_${o_vars[a]} () const\n{\n\treturn ${o_vars[a]}\;\n}" $src
				fi
			done
		fi
	fi
	sed -i '/./,/^$/!d' $inc
	if [ $template_flag -eq 0 ]; then
		sed -i '/./,/^$/!d' $src
	else
		sed -i "s/class/template<$templates2> class/" $inc
		sed -i '/./,/^$/!d' $src
	fi
else
	echo "You are not in the project directory! Exit"
fi
