#!/bin/sh
set -e
echo $(pwd)
source $(pwd)/.prj
args=("$@")
class_name=${args[0]}
args=("${args[@]:1}")
args[0]=": ${args[0]}";
if [ ${#args[@]} -ne 0 ]; then
	separator=", " # e.g. constructing regex, pray it does not contain %s
	regex="$( printf "${separator}%s" "${args[@]}" )"
	parents="${regex:${#separator}}" # remove leading separator
fi

if [ -e "include" -a -e "src" ]; then
	d=$(date +%x\ %X)
    cp /etc/cpprj/cls_dummy.hpp include/$class_name.hpp
    cp /etc/cpprj/cls_dummy.cpp src/$class_name.cpp
    sed -i "s|\$cls_parents|$parents|g" include/$class_name.hpp
    sed -i "s|\$cls|$class_name|g" include/$class_name.hpp
    sed -i "s|\$cls|$class_name|g" src/$class_name.cpp
    sed -i "s|\$auth|$auth|g" include/$class_name.hpp
    sed -i "s|\$d|$d|g" include/$class_name.hpp
    sed -i "s|\$auth|$auth|g" src/$class_name.cpp
    sed -i "s|\$d|$d|g" src/$class_name.cpp
    sed -i "s|SOURCE_FILES^|SOURCE_FILES\n\t\tsrc/$class_name.cpp|" CMakeLists.txt
else
    echo "You are not in the project directory! Exit"
fi
