#!/bin/sh
set -e
source .prj
args=("$@")
class_name=${args[0]}
args=("${args[@]:1}")
function join { local IFS="$1"; shift; echo "$*"; }
if [ ${#args[@]} -ne 0 ]; then
	parents=join ', ' "${args[@]}"
fi

if [ -e "include" -a -e "src" ]; then
	d=$(date +%x\ %X)
    cp /etc/cpprj/cls_dummy.hpp include/$class_name.hpp
    cp /etc/cpprj/cls_dummy.cpp src/$class_name.cpp
    sed -i "s|\$cls_parents|$parents|g" include/$class_name.hpp
    sed -i "s|\$cls|$class_name|g" include/$class_name.hpp
    sed -i "s|\$cls|$class_name|g" src/$class_name.cpp
    sed -i "s|\$auth|$auth|g" include/$class_name.hpp
    sed -i "s|\$d|$d|g" src/$class_name.cpp
    sed -i "s|SOURCE_FILES^|SOURCE_FILES\n\t\tsrc/$class_name.cpp|" CMakeLists.txt
else
    echo "You are not in the project directory! Exit"
fi
