#!/bin/bash

set -e
if [ -e "include" -a -e "src" ]; then
	if [ -e "include/$1.hpp" -a -e "src/$1.cpp" ]; then
		rm include/$1.hpp src/$1.cpp
		sed -i "/$1/d" CMakeLists.txt
	fi
else
	echo "You are not in the project dir. Exit"
fi
